---
- hosts: ubuntu
  vars:
    http_proxy: ""
    https_proxy: ""
    no_proxy: ""
    configure_proxy: "{{ True if http_proxy or https_proxy else False }}"
  environment:
    HTTP_PROXY: "{{ http_proxy }}"
    HTTPS_PROXY: "{{ https_proxy }}"
    NO_PROXY: "{{ no_proxy }}"
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  tasks:
    - name: Configure proxy and install cloud-init
      become: yes
      block:
      - name: Configuring environment proxy
        lineinfile:
          dest: /etc/environment
          line: "{{ item.key }}={{ item.value }}"
        with_dict:
          HTTP_PROXY: "{{ http_proxy }}"
          HTTPS_PROXY: "{{ https_proxy }}"
          NO_PROXY: "{{ no_proxy }}"
          http_proxy: "{{ http_proxy }}"
          https_proxy: "{{ https_proxy }}"
          no_proxy: "{{ no_proxy }}"
        when: configure_proxy|bool|default(false)
      - name: Update all packages to the latest version
        apt:
          upgrade: dist
          update_cache: yes
      - name: Install required packages
        apt:
          name: "{{ item }}"
          state: present
          update_cache: yes
        with_items:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - cloud-init
          - cloud-utils
          - vim
      - name: Copy cloud-init configuration files
        copy:
          owner: root
          group: root
          mode: 0644
          src: "{{ item }}"
          dest: /var/lib/cloud/seed/nocloud-net/
        with_items:
          - files/cloud-init/user-data
          - files/cloud-init/meta-data
    - name: Ensure that proper .vimrc is copied
      copy:
        src: files/.vimrc
        dest: ~/.vimrc
